###
GET http://localhost:4000/find
content-type: application/json

###


POST http://localhost:4000/insert
content-type: application/json

{
    "title": "test",
    "body": "Wed, 21 Oct 2015 18:27:50 GMT",
    "author": "Janne"
}


### Delete
DELETE http://localhost:4000/delete/6076df1c1e726017a45d0219

